### ISSUE TITLE
[Feature request] Allow the deletion of shopping individual shopping items

### ISSUE THREAD

**Issue by tuto193** [RayLeaf-Studios/PocketPlan#61]
## What?
Allow the deletion of individual shopping items from a list/category.

## Why?
Currently the only way to delete shopping items from a list is to either:
- Delete the whole list, or
- Think of another item to take the item-to-delete's place, or
- This:
  1. Uncheck all items.
  2. Check the individual item(s) that are to be deleted.
  3. (From the dots menu) select the option `Remove checked items'... done.
  
This process is quite cumbersome, and deleting individual items (custom or not) from a current list (or category) should be more seamless, since mistakes could happen e.g. one might add a(n) (custom?) item by mistake, and one just might want a quick way to undo the mistake.

## Suggestion
Maybe add another option to the item edit menu, that allows for the deletion of said item (?).

**Comment by JakeGonder** [comment]
Hey @tuto193, you can delete individual items by swiping them left or right. There is quite a few of these interactions in PocketPlan (like pressing and holding, swiping, and tapping) which are not immediately obvious due to no UI element indicating their existence, which is obviously a tradeoff between usability and keeping the UI as minimalistic as possible. This is why we added a "HowTo" section accessible from the side menu, listing every functionality in detail.

**Comment by tuto193** [comment]
Oh, my bad. I just noticed this. Swiping to the side was actually my first thought, but I seem to habe been swiping the category and not the actual item. Thanks a lot for the quick response!

**Comment by JakeGonder** [comment]
No worries, it's definetly a bit finicky since the items are so thin, we might try out slightly increasing their height, or maybe making this adjustable via an option.
